# Generated by Django 5.2.4 on 2025-07-12 09:46

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField()),
                ('negotiable', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Ethnic Wear', 'Ethnic Wear'), ('Dresses & One-Pieces', 'Dresses & One-Pieces'), ('Outerwear', 'Outerwear'), ('Activewear', 'Activewear'), ('Footwear', 'Footwear'), ('Accessories', 'Accessories'), ('Winter Wear', 'Winter Wear'), ('Unisex/Free Size', 'Unisex/Free Size'), ('Others', 'Others')], default='Others', max_length=50)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=10)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Free Size', 'Free Size')], default='Free Size', max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Gently Used', 'Gently Used'), ('Fair', 'Fair')], default='Gently Used', max_length=20)),
                ('occasion', models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Festive', 'Festive'), ('Partywear', 'Partywear'), ('Others', 'Others')], default='Casual', max_length=20)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('All-Season', 'All-Season')], default='All-Season', max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('swapped', 'Swapped'), ('redeemed', 'Redeemed')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
        ),
    ]
