# Generated by Django 5.2.4 on 2025-07-12 08:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='occasion',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Formal', 'Formal'), ('Festive', 'Festive'), ('Partywear', 'Partywear'), ('Others', 'Others')], default='Casual', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=813209, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('All-Season', 'All-Season')], default='All-Season', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Ethnic Wear', 'Ethnic Wear'), ('Dresses & One-Pieces', 'Dresses & One-Pieces'), ('Outerwear', 'Outerwear'), ('Activewear', 'Activewear'), ('Footwear', 'Footwear'), ('Accessories', 'Accessories'), ('Winter Wear', 'Winter Wear'), ('Unisex/Free Size', 'Unisex/Free Size'), ('Others', 'Others')], default='Others', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Gently Used', 'Gently Used'), ('Fair', 'Fair')], default='Gently Used', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Free Size', 'Free Size')], default='Free Size', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
