# Generated by Django 5.2.4 on 2025-07-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverification_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='points',
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
